export { default as NavBar} from './HomePage/navBar/NavBar'
export { default as Footer} from './HomePage/footer/Footer'
export { default as Header} from './HomePage/header/Header'
export {default as Home} from './HomePage/Home'
export {default as LoginPage} from './LoginPage/LoginPage'
export {default as ConnectedPage} from './ConnectedPage/ConnectPage'
export {default as QrCodePage} from './QrCodePage/QrCodePage'
export { default as DashboardPage } from './DashboardPage/DashboardPage'
export {default as DashboardPageProfile }  from './DashboardPageProfile/DashboardPage'
